### ISSUE TITLE
implement FONEM

### ISSUE THREAD

**Issue by chrislit** [chrislit/abydos#22]
http://www.youscribe.com/catalogue/presse-et-revues/savoirs/sciences-humaines-et-sociales/fonem-un-code-de-transcription-phonetique-pour-la-reconstitution-1076317

**Comment by Yomguithereal** [comment]
Hello @chrislit. I've just finished a JavaScript implementation of this algorithm based on the paper. You can find it [here](https://github.com/Yomguithereal/talisman/blob/master/src/phonetics/french/fonem.js). If you implement it in python, I'll be very interested by your feedback on the paper because I found it very confusing about rule ordering and I am not sure I got it right.

Have a good day.

**Comment by chrislit** [comment]
completed in 1b1e601a1e529e6cabd1d63e2da19ce4a1fad8fd
